### ISSUE TITLE
Brian's copy editing read-through

### ISSUE THREAD

**Issue by briandoconnor** [broadinstitute/genomics-in-the-cloud#117]
## About

A ticket for me to track when I've read through the copy edit version of each chapter

* [x] Chapter 0 - Preface
* [x] Chapter 1 
* [x] Chapter 2 
* [x] Chapter 3 
* [x] Chapter 4 
* [x] Chapter 5  
* [x] Chapter 6 
* [x] Chapter 7 
* [x] Chapter 8 
* [x] Chapter 9 
* [x] Chapter 10 
* [x] Chapter 11 -- I picked up my pace here
* [x] Chapter 12 
* [x] Chapter 13 
* [x] Chapter 14 

[Final to production GDrive folder](https://drive.google.com/drive/folders/1aLkzn1m_ArpizBpK8gSVnopetGBC52qx)

[Word list](https://docs.google.com/document/d/1cPOvqoZ49PWt0n64UI0zZ5t6OuFJ9FysWeDeuEyr5ic/edit#)

[Temp doc for text](https://docs.google.com/document/d/1DQnAeO7TcHQSoE-8H5JuD_m-uSBLFMqpSvmGWscSzWo/edit)

See #47 for my previous read-through which I'll reference here if needed

## CE contacts

* Katie Tozer is the production editor
* Kristen Brown  Manager
* Bob Russell, copyeditor

## TODO

* [ ] Katie asks, I have some figure-related questions I'd like to get straightened out right away. Could you please take a look at the [Figure Log](https://docs.google.com/spreadsheets/d/1emrDJlBZQzJh5ArfgoVqidZnmYmnSIiHsNptXhIHPQQ/edit?usp=sharing) I've shared with you and respond to the notes highlighted in orange?
* [ ] add to preface in suggest mode

## Instructions

* Please do not accept any changes—just add your own comments or edits via Suggestions on top of Bob's edits.
* if you disagree with an edit or would like to modify an edit, please use the Reply function for the specific edit to indicate so
* Please do not delete any of the edits, even if you reject it; otherwise, I won’t be able to track what was done. Also, you do not need to explicitly accept each edit; if you do not reject (or modify) an edit, we consider it accepted.

## Schedule

Here is your revised schedule (from Katie):
* Copyediting: 2/3–11 
* Author's review of copyedits: 2/12–21 (You'll review the marked-up Word file and the Word List, replying to any queries and making any edits. DO NOT accept any Track Changes at this time.)
* QC1: 3/9–16 (You'll see a PDF in the book's theme with all of the edits from copyediting implemented into the source files. During this time, an indexer will also be indexing the source files.)
* Author's review of index: 3/17–20 (After you send me your QC1 edits, I'll generate a draft index and send it to you for review.)
* QC2: 3/23–24 (This is your last review, and will have all of the edits from QC1—both your own and those of the proofreader—and any redrawn figures incorporated. During this time, the indexer will be entering any index edits you've requested. We'll do our best to keep this date as-is so you can have the weekend in addition to the standard two-day review.  If possible, I'll send this by EOD the preceding Friday so you'd have the weekend as well.)
* Files to printer: 3/27 (The ebook versions will be available within a week of this date. Print books will begin appearing about 18 business days after the FTP.)

Additional materials:
* Please ask for the Foreword to be turned in by 3/5 so we can get it proofread.
* Could you take a pass at the Preface and add Acknowledgments over the weekend? I'm guessing a list of software would fit best in the Preface as well. Is that correct, or what are your thoughts on this piece?
* If we're adding a Glossary, I definitely want a copyeditor looped in. If you can, please send us the Glossary Monday. Worst case scenario, you could add your Glossary terms to Word List Bob will create during the Copyedit Review (2/12–19). That would still go a long way toward making sure all terms are being used, capitalized, and abbreviated consistently throughout the text.

**Comment by vdauwera** [comment]
Addressed all issues except text-heaviness… will fix that in v2!
