### ISSUE TITLE
Brian's read-through

### ISSUE THREAD

**Issue by briandoconnor** [broadinstitute/genomics-in-the-cloud#47]
A ticket for me to track when I've read through the latest version of each chapter

* [x] Chapter 1 -- I left feedback for Geraldine 20191207
* [x] Chapter 2 -- feedback left for Geraldine 20191231
* [x] Chapter 3 -- feedback left for Geraldine 20200102
* [x] Chapter 4 -- feedback given to Geraldine, ready for preview release 
* [x] Chapter 5 -- feedback given to Geraldine 20191202, ready for preview release 
* [x] Chapter 6 -- feedback given to Geraldine 20200104
* [x] Chapter 7 -- feedback given to Geraldine 20200104
* [x] Chapter 8 -- feedback given to Geraldine 20200105
* [x] Chapter 9 -- feedback given to Geraldine 20200105
* [x] Chapter 10 -- feedback given to Geraldine 20200112
* [x] Chapter 11 -- feedback given to Geraldine 20200112
* [x] Chapter 12 -- feedback given to Geraldine 20200112, re-reviewed the chapter 20200120
* [x] Chapter 13 -- feedback given to Geraldine
* [x] Chapter 14 -- feedback given to Geraldine 20200113

We might (optionally) work on the following appendices 
* [ ] Appendix 1 - WDL
* [ ] Appendix 2 - Notebook reference
* [ ] Appendix 3 - FISS Library 

Figures check:

* [ ] Chapter 1
* [ ] Chapter 2
* [ ] Chapter 3
* [ ] Chapter 4
* [ ] Chapter 5
* [ ] Chapter 6
* [ ] Chapter 7
* [ ] Chapter 8
* [ ] Chapter 9
* [ ] Chapter 10
* [ ] Chapter 11
* [x] Chapter 12 -- in progress
* [x] Chapter 13
* [x] Chapter 14

**Comment by vdauwera** [comment]
addressed all issues
